### ISSUE TITLE
Add marketplace annotations

### ISSUE THREAD

**Issue by luebken** [FrangipaneTeam/provider-flexibleengine#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The provider is not getting rendered nicely in the marketplace.

### Expected Behavior

For a nice rendering of the provider in the Marketplace, we like to ask to put the Crossplane standard annotations into the crossplane.yaml: https://docs.crossplane.io/v1.10/reference/xpkg/#object-annotations. This would also make sure the marketplace listing links back to this GitHub repo. If you need help, don't hesitate to reach out.

### Environment

* Universal Crossplane Version:
* Provider Version:

**Comment by gaetanars** [comment]
Thanks @luebken for your issue.
We release a new version as soon as possible to fix that.
