### ISSUE TITLE
[DOC] standardize namespace in examples

### ISSUE THREAD

**Issue by azrod** [FrangipaneTeam/provider-flexibleengine#90]
Actually use `crossplane-provider` for namespace parameter in examples files. 

It necessary to standardize tu upbound conventionnal. 

Old namespace : `crossplane-provider`
New namespace: `upbound-provider`

_Originally posted by @azrod in https://github.com/FrangipaneTeam/provider-flexibleengine/pull/89#discussion_r1069992058_

**Comment by gaetanars** [comment]
It seems to be the same in the Official Upbound Providers : documentation refers to `upbound-system` namespace and examples refers to `crossplane-system `namespace.

**Comment by azrod** [comment]
Thanks for the information
